version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: betnetics_test
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - '6379:6379'

  app:
    build: .
    container_name: betnetics_test
    depends_on:
      - postgres
      - redis
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: 'postgresql://postgres:postgres@postgres:5432/betnetics_test'
      REDIS_HOST: redis
      REDIS_PORT: 6379
    command: sh -c "npx prisma migrate deploy && npm run start:dev"
    volumes:
      - .:/app

volumes:
  pgdata:
