version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
      interval: 5s
      retries: 5
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: betnetics_test
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5433:5432'

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - '6380:6379'

  app:
    build: .
    container_name: betnetics_test
    depends_on:
      - postgres
      - redis
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: 'postgresql://postgres:postgres@postgres:5432/betnetics_test'
      REDIS_HOST: redis
      REDIS_PORT: 6379
    entrypoint: ["./wait-for-it.sh", "postgres:5432", "--"] 
    command: sh -c "npx prisma migrate deploy && npm run start:dev"
    volumes:
      - .:/app

volumes:
  pgdata:
